### ISSUE TITLE
using goblin for installations

### ISSUE THREAD

**Issue by barelyhuman** [wabarc/wayback#151]
A small concern about the deps of the project
`https://github.com/btcsuite/btcd`

is a dep in the packages and I don't see why this is needed by this package 

The other reason for this issue is that you could use goblin for installation and I've added support to resolving go packages from github.com into goblin

Here's a screenshot of the installation working 
This will be live in the next few hours

![Screenshot 2022-03-18 at 10 52 18 PM](https://user-images.githubusercontent.com/43572006/159052920-b9c45e1d-3170-4904-96a3-1075f6a23020.png)

**Comment by waybackarchiver** [comment]
Thank you for your works.

The mod graph about `github.com/btcsuite/btcd` is `github.com/wabarc/rivet => github.com/libp2p/go-libp2p-core => github.com/btcsuite/btcd`

Installing binaries from on-demand Gobinaries has some limitations, such as long compilation times, server instability, lack of replicability, and so on. For this project, we're working on an install script that will allow users to download the compiled binaries directly from GitHub Releases.

Kindly let us know if you have any hints.

**Comment by barelyhuman** [comment]
You can use [bina](https://bina.egoist.sh/)  if the binaries already exist, though you might need to follow the naming standards for it to detect the needed binaries. 

As for long compilation times, goblin doesn't have a CDN limitation and totally depends on how long the mods take to compile. 

So both should work as intended but yes, if you are expecting build times over 30 seconds you are better off going with [bina](https://bina.egoist.sh/)

**Comment by waybackarchiver** [comment]
I tried to install `wayback` and `hub` from bina, but gotten no output.

```sh
curl -sf https://bina.egoist.sh/github.com/github/hub/cmd | sh
```

```sh
curl -sf https://bina.egoist.sh/wabarc/wayback/cmd/wayback | sh
```

**Comment by barelyhuman** [comment]
Oh no no, 
Bina just hit's the releases page on github so the command for the wayback cli would be downloaded from your releases page. 

the command would be like 
```sh
curl -fsSL https://bina.egoist.sh/wabarc/wayback | sh
```

whatever matches with the requested system will be downloaded as a binary

**Comment by waybackarchiver** [comment]
Thanks for the update.

Bina appears being a viable alternative, we'll see that in the installation instructions, thank you.
