### ISSUE TITLE
Generate a singleFile html file

### ISSUE THREAD

**Issue by theChrisWei** [wabarc/wayback#183]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Not related to a probelm

**Describe the solution you'd like**
see https://github.com/gildas-lormeau/SingleFileZ or 
https://github.com/gildas-lormeau/SingleFile

**Comment by waybackarchiver** [comment]
We used to store single files to IPFS using [obelisk](https://github.com/wabarc/obelisk), but we removed that feature because some files were too large, and now it appears that we must attach single files.
